{
 "title": "Conduit Station",
 "tags": [ "conduit" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Clients",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 0 },
   "targets": [
    { "expr": "conduit_connected_clients", "legendFormat": "Connected" },
    { "expr": "conduit_connecting_clients", "legendFormat": "Connecting" }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(conduit_bytes_uploaded[1m]) * 8",
     "legendFormat": "Upload bitrate"
    },
    {
     "expr": "rate(conduit_bytes_downloaded[1m]) * 8",
     "legendFormat": "Download bitrate"
    }
   ]
  },
  {
   "title": "Station Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "conduit_is_live" }
   ]
  },
  {
   "title": "Total Traffic",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "conduit_bytes_uploaded + conduit_bytes_downloaded"
    }
   ]
  },
  {
   "title": "Configured Bandwidth Limit",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "conduit_bandwidth_limit_bytes_per_second"
    }
   ]
  }
 ]
}